site_name: Jiu-Jitsu by Narrationless
#site_url: https://narration-less.github.io/jiu-jitsu-vault
site_dir: public

theme:
  name: material
  palette:
    scheme: slate
    primary: blue grey
    accent: light blue

# Extensions
markdown_extensions:
  - toc:
      permalink: true

  - footnotes
  - attr_list
  - pymdownx.highlight
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.emoji
  - admonition

plugins:
  - search
  - roamlinks
  - mkdocs-video:
      is_video: True
